### ISSUE TITLE
Can't find variable: Symbol

### ISSUE THREAD

**Issue by KakarN** [mobxjs/mobx#1582]
I am trying to integrate mobx into my react-native project. But I was stuck when I tried to import Provider into the main App.js.

I have this error:

`Error: "Can't find variable: Symbol Evaluating module://mobx-react.js Evaluating module://App.js Loading module://App.js" in`

On further checking I found that the latest version of the mobx/mobx-react was the problem. When I installed the old version, the error was gone.

You can check the latest mobx/mobx-react version [snack here](https://snack.expo.io/@kakarn/mobx---latest-verstion), which does not work.

And the old version of mobx/mobx-react version of [snack here](https://snack.expo.io/@kakarn/mobx---old-version), which does work.

**Comment by mweststrate** [comment]
Can you file this issue in the mobx-react repo? A work around for this
moment would be to use a Symbol polyfill, or downgrade mobx-react to 5.2.0

Op vr 8 jun. 2018 om 12:55 schreef KakarN <notifications@github.com>:

**Comment by KakarN** [comment]
Okay. No problem!

**Comment by mweststrate** [comment]
Please close issue next time when opening another :)

Solved in mobx-react@5.2.2

**Comment by mrkhoros** [comment]
This issue still stands , you suggest we should use a lower version ? can you specify with version would work on Android ?

**Comment by mweststrate** [comment]
See the top of the readme

Op zo 17 jun. 2018 20:22 schreef mrkhoros <notifications@github.com>:

**Comment by pincheira** [comment]
Running `"mobx-react": "^5.2.3"` and still seeing this on Android.

**Comment by mweststrate** [comment]
Again, see top of the readme:

MobX >=5 runs on any browser with [ES6 proxy support](https://kangax.github.io/compat-table/es6/#test-Proxy). It will throw an error on startup on older environments such as IE11, Node.js <6 or React Native Android on old JavaScriptCore [how-to-upgrade](https://github.com/react-community/jsc-android-buildscripts#how-to-use-it-with-my-react-native-app).

So either, use MobX 4 (yes it is still supported) or upgrade your JavaScript Core

**Comment by mweststrate** [comment]
Are you using Mobx 4 or 5?

**Comment by EyreGe** [comment]
"mobx": "^5.0.4",
 "mobx-react": "^5.2.5",
 still seeing this on Android.

**Comment by mweststrate** [comment]
For React Native android user, please upgrade your [JSC version](https://github.com/react-community/jsc-android-buildscripts#how-to-use-it-with-my-react-native-app) or downgrade to MobX 4
